src/pages/SteppingStone/SteppingLayout.tsx, src/pages/SteppingStone/components/SteppingBody.tsx
#129
- 
- 기존에 회의 입장할 때 방장이 입력한 회의명이 아니라 '에이셉 전체회의' 라는 문구가 하드코딩 되어있던 것이 문제였는데요.
회의 입장페이지에서 해당 회의가 유효한 회의인지 (이미 확정된 회의인지) 확인하는 api를 쏘는데, 해당 요청에 대한 응답으로 회의명을 받아올 수 있도록 서버측에 요청해서 해결했습니다.
- 찬우오빠가 모든 퍼널의 공통적인 요소들을 SteppingStone이라는 공통컴포넌트로 구현했는데, 그래서 회의명에 해당하는 부분도 'SteppingBody'라는 공통 컴포넌트로 나타내고 있었습니다. 이 컴포넌트에 api 응답으로 받아온 회의명을 prop으로 넘겨주어야해서, SteppingBody 컴포넌트에 meetingTitle이라는 prop을 추가했고, 회의 입장 페이지 외에는 이 prop이 필요하지 않기 때문에 type은 undefined를 허용했습니다.
- 워낙 공통컴포넌트가 깔쌈하게 되어있었어서 이 한 페이지를 위해 prop을 추가한게 썩 만족스럽지는 않은데... 전역상태관리로 해결했어야하나 싶기도 하구요...
-
https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/55528304/96dcada8-352d-4032-b006-df294e2f91d6
입장페이지 새로고침하는 영상인데, 보다시피 api 응답 받아오는데 시간이 걸려서 잠깐동안 빈 글자로 나옵니다 ㅠㅠ
흠 이걸 어떻게 해결하면 좋을지....
=> [Feat/#169] 회의 입장페이지에서 회의명 보여주기

index.html, public/robots.txt, public/sitemap.xml, src/pages/SteppingStone/SteppingLayout.tsx, src/utils/toast/ToastContainer.tsx, src/utils/toast/copyLink.ts
#178 
- toast 를 생성할 땐 id값을 넣어줘야 예상 가능하게 작동한다 (광클해도 한 번만 뜹니다. dismiss같은 속성도 이용가능하구요)
- toastContainer는 app (route)에 넣는 것이 권장됩니다.
- toast는 id를 사용하면 연속적으로 마구잡이로 생성되지 않습니다.
- limit속성은 최대 몇개 띄울 것이냐 인데 id가 없어도 동작은하지만 한개를 계~~속 띄우게되니 id를 사용해야합나다.
-없음!
https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/81609304/71eea8f9-8380-43ec-999c-a9397806b1f7
=> [ Fix / toastCreate / #178 ] toast 무한 생성 버그 수정

src/components/atomComponents/Text.tsx, src/pages/BestMeetTime/components/bestMeetTime/BestMeetTime.tsx
- '사파리 명조체 이슈' 라고 하기는 했는데, 오로지 방장페이지의 제목 부분만 명조체가 나오는 걸 보아 브라우저별 폰트 호환성 문제가 아니라 다른 방향으로 접근해야겠다는 생각이 들었습니다.
- 명조체로 나오는 부분을 개발자도구에서 찍어보니 역시 font-family 속성 자체가 없드라구요... 해당 요소에 폰트가 적용이 안된 것이었습니다.
- 그래서 사파리 외에 다른 브라우저에서도 사실 해당 부분에 폰트가 적용이 안되어있습니다. 단지 애플 기본 폰트와 Pretendard가 크게 다르게 생기지 않아서 티가 안나는 것이었습니다.
- 역시 문제의 원인을 파악하는 것은 중요합니다.
- 해당 부분이 '현재까지 모인' + '1(변동되는 부분)' + '명을 위한 최적의 회의시간이에요' 이렇게 텍스트가 구성되어야 하는데, Text 공통 컴포넌트의 children으로 이렇게 혼합된 요소를 넣을 수가 없어서, 찬우오빠가 일단 빠른 구현을 위해 Text 컴포넌트가 아닌 div를 사용하다가 폰트 적용하는걸 깜빡한 것 같습니다. 
<br/>
전자는 Pretendard, 후자는 Apple Gothic인데 특히 ㅎ의 모양이 다른 걸 보실 수 있습니다. 그치만 자세히보지 않으면 티가 안남<br/>
더불어서 원래 '명'이라는 글자또한 초록색이어야 하는데 현재 배포본에는 '명'도 흰색인걸 보실 수 있습니다
- 그래서 Text 컴포넌트의 맹점에 대해서 생각하게 되네요... 복잡한 chlidren을 넣기가 너무 까다로워집니다. 변동되는 인원수(number)를 Text컴포넌트의 자식으로 넣기 위해서 Text 컴포넌트의 자식 type에 …
=> [Feat/#184] MacOS 사파리 명조체

src/pages/SteppingStone/SteppingLayout.tsx
- state 변경 시기를 항상 주의할 것
- 회의명 보여주는 부분을 처리하면서 원래 없던 setState를 추가했는데, 현재 이 방이 확정된 회의인지 아닌지를 판단하기 전에 setState를 실행하여 오류가 나게되는 간단한 상황이었습니다. 순서를 조정하여 해결하였습니다.
https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/55528304/54d246d6-7beb-4c8a-b0e3-6d1a40365eee
확정된 회의이므로 바로 리다이렉트되는 모습
=> [Feat/#188] 확정된 회의 링크 입장시 리다이렉션

src/utils/changeBrowser.ts
- 스킴이라는거... 생소하네요 자료 찾기가 어려운 것 같아요 특히 삼성인터넷이다보니...
- 카톡 인앱브라우저를 피하는 기능을 담당하는 changeBrowser.ts라는 파일의 `inappbrowserout`이라는 function에서 `navigator.userAgent`라는 값으로 현재 어떤 인앱으로 들어왔는지를 확인합니다. kakaotalk이라면 외부 브라우저를 호출하고, 이후 안드로이드라면 `location.href =
'intent://' +
target_url.replace(/https?:\/\//i, '') +
'#Intent;scheme=http;package=com.android.chrome;end';`라는 코드를 통해 크롬을 띄우는 것이 원래 코드였습니다. 그런데 의도와는 다르게 크롬이 아니라 크롬/삼성인터넷 중 선택하는 모달창이 나왔었죠. 그 모달창에서 삼성인터넷을 선택하면 다시 같은 분기가 실행되어 같은 모달창이 뜨는 것이었습니다. 그 모달을 띄울지 말지를 조정하는 방법을 찾지 못했고 (스킴을 바꿔야하는걸까요.. 바꾼다면 어떻게...) 차선책으로 아예 안드로이드일 경우에- 라는 if분기를 삭제하니 모달이 뜨지 않고 바로 삼성인터넷으로 연결이 되었습니다.
- 혹시모르니 여러 브라우저에서 qa가 필요할 것 같습니다.
=> [Fix/#195] 삼성인터넷/크롬 선택지 없이 바로 삼성인터넷으로 우회

src/Router.tsx, src/pages/LoginEntrance/components/HostComponent.tsx
#192 
- try catch 로직에서 catch(err) 부분에 err 는 타입이 unknown이다.
- if(axios.isAxiosError(err)) 로직으로 감싸 Axios에러가 맞는지 확인하거나
- if(err.response) 와 같은 타입가드로 타입을 보호? 할 수 있다. (옵셔널체이닝은 에러가 발생함)
- 타입스크립트 잘해봅시다
- https://gxxrxn.github.io/axios-error-type-guard/
- https://s0ojin.tistory.com/34
-
=> [ Fix/#192] host로그인 시 가능시간 입력안함, 비밀번호 유효성 검증에 대한 에러 해결

src/Router.tsx, src/pages/selectSchedule/SelectModal.tsx, src/types/createAvailableSchduleType.ts, src/utils/apis/createHostAvailableSchedule.ts
#194 
- 서버에서 보내주기에 따라, 400코드 에러가 try에서 잡힐 수도, catch에서 잡힐 수도 있다! 서버와 협의 필요.
- 서버에서 리스폰스로 온 값의 에러처리를 할때, 타입스크립트 에서는 isAxiosError와 .response를 이용하여 타입스크립트의 안정성을 지킨다...!
- AxiosResponse -> 요놈 좀 문제가 있는 개념이다. 응답 시 응답 데이터 외의 header나 그외의 것들을 사용해야 하는것 아니라면, 이걸 쓸 필요 없이 그냥 응답 데이터에만 타입 지정해주고 쓰는게 낫다고 GPT가 그랬다. 응답 데이터를 이용하다가 발생한 타입에러에 관한 트러블 슈팅을 하다가 발견했다.
- 400에러 시에만 alert로 전달받은 메세지를 띄우게 함
- 그 외에 catch로 간 에러는 전부 에러페이지로
- try에서도 201코드만 다음페이지 넘어가고 혹시 몰라서 다른건 전부 에러페이지로 가게 뒀다.
- 타입 에러를 수정하려고 GPT에 물어봤더니 AxiosReponse를 지우래서 지웠더니 해결됐음.
- 그래서 아래에 같은 코드를 위처럼 바꿈. 나중에 아래도 axiosresponse 지움. 근데 이거 재훈이형이 썼던데 axiosresponse를 쓴 이유가 따로 있나?
=> [Fix/#194] 선호시간 선택 후 POST시 response 값에 따라 처리 수정

src/components/atomComponents/PasswordInput.tsx, src/pages/createMeeting/components/useFunnel/SetHostInfo.tsx
- type = number를 input에 속성으로 추가하면 안드는 숫자 키패드가 뜬다.
- ios는 이때 뜨긴 하지만, 아예 숫자 키패드가 아니라, 쿼티 자판의 숫자 입력 상태가 뜨는식. 
- 그래서 inputMode = numeric을 추가로 넣어주면 완전 키패드가 뜬다.
- x
- x
=> [Fix/#202] 로그인시 숫자 키패드 뜨게하기

src/pages/BestMeetTime/components/bestMeetTime/confirmModal.tsx, src/pages/selectSchedule/SelectPriorityPage.tsx, src/pages/selectSchedule/SelectSchedulePage.tsx
- try-catch에서 error가 났을 때 alert를 띄우니 alert가 두번씩 뜨는 문제가 발생했습니다. 렌더링이 두번 되는건가 싶어서 useEffect랑 useMemo랑 막 건드려봤는데... (지금 스스로 렌더링 방식에 대한 이해가 너무 부족한게 느껴지더라고요...) 그냥 React.StrictMode때문에 그런것이었습니다..!! 
- React.StrictMode는 언세이프한 코드 감지하기 위해, 개발모드에서 의도적으로 마운팅을 두 번 일으킵니다. 프로덕션 빌드에는 영향을 끼치지 않습니다.
https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/55528304/72d85b10-993c-45ee-92d4-58955e5e3dc7
=> [Feat/#205] 회의 확정시 토큰 삭제 및 입력 단계에서 큐카드로 리다이렉트 

src/components/atomComponents/PasswordInput.tsx, src/pages/selectSchedule/SelectSchedulePage.tsx, src/pages/selectSchedule/components/TimeSelect.tsx
=> Fix/hide password/#215

src/components/atomComponents/Button.tsx, src/components/atomComponents/PasswordInput.tsx, src/components/atomComponents/TextInput.tsx, src/pages/LoginEntrance/components/HostComponent.tsx, src/pages/SteppingStone/components/SteppingBtnSection.tsx, src/pages/createMeeting/components/useFunnel/SetDates.tsx, src/pages/createMeeting/components/useFunnel/SetDuration.tsx, src/pages/createMeeting/components/useFunnel/SetHostInfo.tsx, src/pages/createMeeting/components/useFunnel/SetPlace.tsx, src/pages/createMeeting/components/useFunnel/SetTimes.tsx, src/pages/createMeeting/components/useFunnel/SetTitle.tsx
- 모달에 애니메이션을 부여하기 위해서 transition을 사용해야하는데, 이 transition이 안먹어서 진짜 애를 썼어요...
우선 제가 처음에 모달 부분을 다음과 같이 구조를 짰는데요. 참고로 ModalOverlay는 모달 뒤에 깔리는 불투명한 검정색 배경입니다.
```html
<ModalOverlay>
<BottomSheetModal>
</BottomSheetModal>
</ModalOverlay>
```
이렇게 ModalOverlay로 모달을 감싸놓고, useState로 `isModalOpen` state를 만들어서 state가 바뀔 때마다 ModalOverlay는 position:display와 none을 왔다갔다하고(모달이 없어지면 오버레이도 없어져야하니), BottomSheetModal은 position:fixed; 상태에서 bottom 값을 바꿈으로써 아래에서 위로 올라오도록 위치를 변경했어요. 그 상태에서 transition을 적용하면 아래에서 위로 올라오는 애니메이션이 적용되어야하는데 아무리해도 적용이 안되는겁니다!! ㅠㅠ
- 그래서 처음에는, useState가 변경되는 것과 style이 변경되는 것에 무언가 시간차를 주어야 한다고 생각했어요. 왜냐면 바닐라 자스로 할 때는 실제로 돔 잡아서 style 조작할 때 setTimeout을 주어야 transition 되는 것이 눈에 보이거든요... 그래서 setTimeout도 써보고, 모달 위치 저장하는 state하나를 더 만들어서 useEffect로 조작해보고, …
=> [Feat/#219] 회의 생성 후 바텀 시트 모달

src/pages/selectSchedule/utils/changeApiReq.ts, src/types/createAvailableSchduleType.ts
#247 
/time POST (시간 입력)시에 서버에게 전달했던 id, dayOfWeek 필드가 필요없어서 이를 삭제하고, month와 day에 대해 자릿수 채움이 필요 없도록 통일하게됨에 따라 padStart() 메소드를 삭제함.
```ts
id: item.id.toString(),
month: month.padStart(2, '0'),
day: day.padStart(2, '0'),
dayOfWeek: dateOfWeek,
startTime: item.startTime,
endTime: item.endTime,
priority: item.priority,
```
```ts
month: month,
day: day,
startTime: item.startTime,
endTime: item.endTime,
priority: item.priority,
```
=> fix: /time POST 요청값에서 id와 dayOfWeek 필드 삭제, month와 day에서 padStart 삭제

src/pages/cueCard/CueCard.tsx, src/pages/cueCard/components/CueCardTitle.tsx, src/pages/cueCard/components/Qcard.tsx
- close #254 
padding을 적절하게 맞추고 큐카드 컴포넌트의 background-color을 검정색으로 바꾸어 보기 좋은 모양새로 바꾸었습니다 ..ㅎㅎ
정확히 어떤 모습으로 저장되면 될지 디자인쪽에 요청을 해야할듯합니다.
왜냐면 다음과 같이 배경을 아예 투명하게(png) 뽑는것도 가능하더라구요.
(흰 배경이 없이 큐카드 모양대로 딱 잘려진 것임!!)
근데 자세히보시면 밑에 점선이랑 양옆에 구멍뚫린 부분 보이시죠.. 이 부분을 투명하게 만들 수가 없다보니 어색한 부분도 있긴 합니다.
위 결과본이랑 아래 스크린샷을 남겨주세요! 에 두번째로 올린 결과물이랑 어떤게 더 나을지, 아니면 다른 방안이 있는지 회의 때 간단히 물어보면 좋을듯합니다!
=> [Fix/#254] 큐카드 저장시 레이아웃 변경

src/pages/OverallSchedule/components/OverallScheduleTable.tsx, src/pages/OverallSchedule/contexts/useClickContext.ts, src/pages/selectSchedule/components/SelectScheduleTable.tsx, src/pages/selectSchedule/components/selectTimeSlot/hooks/useSlotSelection.ts, src/pages/selectSchedule/contexts/useScheduleStepContext.ts, src/pages/selectSchedule/contexts/useSelectContext.ts, src/pages/selectSchedule/utils/changeApiReq.ts
- close #250
탭투탭 로직을 관할하는 `useSlotSelection.ts`에서 `removeOverlappedSlots`라는 새로운 함수를 추가했습니다.
```ts
// 현재 선택한 '탭투탭'의 종료시간(endSlot)과 그 시간이 속하는 날짜(dateOfStartSlot)을 받아옵니다.
// 시작시간(startSlot)은 context로 관리되고 있기 때문에 인자로 넘겨줄 필요가 없습니다.
const removeOverlappedSlots = (endSlot: string, dateOfStartSlot: string) => {
const selectedSlotsPerDate = Object.fromEntries(
Object.entries(selectedSlots).filter(([, slot]) => slot.date === dateOfStartSlot),
);  // 선택된 블록들 중 현재 선택한 탭투탭과 같은 날짜인 것만 필터링합니다. (다른 날짜에 속하는 블록은 확인할 필요없음)
Object.entries(selectedSlotsPerDate).forEach( // 같은 날짜의 블록들을 탐색하면서...
([id, { startSlot: selectedStartSlot, endSlot: selectedEndSlot }]) => {
const startSlotTime = startSlot && startSlot.split('/').pop();
const endSlotTime = endSlot.split('/').pop();
if (
startSlotTime &&
endSlotTime && …
```
=> [Feat/#250] 탭투탭에서 블록이 겹쳐서 쌓이는 문제 해결

src/pages/selectSchedule/components/selectTimeSlot/hooks/useSlotSelection.ts
- close #257 
다음 로직을 추가했습니다.
```ts
let newSelectedSlot: SelectSlotType;
if (startSlot > targetSlot){
newSelectedSlot = {
date:dateOfStartSlot,
startSlot:targetSlot.substring(targetSlot.lastIndexOf('/')+1),
endSlot:startSlot?.substring(startSlot.lastIndexOf('/')+1),
priority:0,
}
} else {
newSelectedSlot = {
date:dateOfStartSlot,
startSlot:startSlot?.substring(startSlot.lastIndexOf('/')+1),
endSlot:targetSlot.substring(targetSlot.lastIndexOf('/')+1),
priority:0,
}
}
```
`startSlot > targetSlot` 이라면, 즉 현재 선택한 종료시간(targetSlot)이 startSlot보다 앞선 시간이라면,
그 순서를 바꿔서 새로운 블록을 생성합니다.
https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/55528304/351cff78-4553-4bc9-a200-345ad4bb6e51
=> [Feat/#257] 탭투탭 아래에서 위로 선택이 가능하도록 처리

src/Router.tsx, src/pages/LoginEntrance/components/HostComponent.tsx, src/utils/apis/useGetTimetable.ts
- close #252
시간표 조회 api를 구현하는 `useGetTimetable.ts`에서 axiosError가 발생하면 에러 코드를 throw하여 이를 useQuery에서 받을수 있게 합니다. 에러 코드가 409라면 큐카드로 navigate합니다.
처음에는 다음과 같이 코드를 작성했습니다.
```ts
export const useGetTimetable = (meetingId?: string) => {
const navigate = useNavigate();
if (meetingId === undefined) {
navigate('/error');
throw new Error('잘못된 회의 아이디입니다.');
}
const { data, isLoading, error } = useQuery({
queryKey: ['getTimetable', meetingId],
queryFn: () => getTimetable(meetingId),
retry: 0,
});
useEffect(
() => {
if (error && (error as ErrorType).errCode === 409) {
navigate(`/q-card/${meetingId}`);
}
},
[error, navigate, meetingId],
);
return { data, isLoading, error };
};
```
그러나 이렇게하면 다음과 같은 오류가 발생합니다.
`useGetTimetable.ts:61 Warning: Cannot update a component (`BrowserRouter`) while rendering a …
=> [feat/#252] 이미 확정된 회의의 시간표를 조회하면 큐카드로 이동

src/pages/selectSchedule/components/selectPriority/PriorityColumn.tsx, src/pages/selectSchedule/components/selectPriority/PriorityDropdown.tsx
- close #272 
```
const priority = selectedEntryId ? selectedSlots[selectedEntryId].priority : 0;
```
위로직은 id가 0일 때, 즉 첫번째 원소일때도 falsy한값이므로 무조건 0으로 반환하기에 null임을 체크해주었습니다.
```
const priority = selectedEntryId !== null ? selectedSlots[selectedEntryId].priority : 0;
```
구현방식에 언급하였습니다!
https://github.com/user-attachments/assets/71347490-3975-41b2-8afb-fcfbb9d67903
=> [ Hotfix/#272 ] 시간 배열의 0번째는 시간표에 우선순위 적용안되는 이슈 해결

src/components/timetableComponents/Timetable.tsx, src/components/timetableComponents/parts/Slot.tsx, src/components/timetableComponents/parts/SlotTitle.tsx, src/components/timetableComponents/types.ts, src/pages/overallSchedule/components/OverallScheduleColumn.tsx, src/pages/overallSchedule/components/OverallScheduleTable.tsx, src/pages/selectSchedule/components/SelectScheduleTable.tsx, src/pages/selectSchedule/components/selectPriority/PriorityColumn.tsx, src/pages/selectSchedule/components/selectTimeSlot/SelectionColumn.tsx, src/pages/selectSchedule/utils.ts
- close #285
좌측이 30분 단위가 있을 때, 우측이 30분 단위가 없을 때인데요.
좌 -> 우로 갈때 달라지는 점은 3가지 입니다.
1. SlotTitle(좌측에 세로로 시간을 나타내는 6,7,8,9,...24)의 간격이 줄어듦
2. 한 Slot(30분)의 높이가 줄어듦
3. 30분 단위에 대한 점선이 없어짐
1번은 SlotTitle 컴포넌트에 적용되어야 하는 변화이고,
2,3번은 Slot 컴포넌트에 적용되어야 하는 변화입니다.
SlotTitle 컴포넌트와 Slot 컴포넌트 모두 세가지의 시간표 컴포넌트에서 공통 컴포넌트로 사용되고 있는 것이기 때문에
이 변화를 모두 prop을 추가하여 적용하려면 prop에 대한 의존성이 증가하고 코드량이 늘어나기 때문에
이 문제를 최소화하기 위해, SlotTitle에만 prop을 새로 만들어 내려주기로 했습니다.
따라서 SlotTitle에 slotUnit prop('HALF' | 'HOUR')을 내려주어, 이에 따라 간격을 조절합니다.
```js
// SlotTitle.tsx
const SlotTitleWrapper = styled.div<{ $slotUnit: 'HALF' | 'HOUR' }>`
display: flex;
flex-direction: column;
gap: ${({ $slotUnit }) => ($slotUnit === 'HALF' ? '1.4rem' : '0.4rem')};
margin-top: 3.3rem;
`;
```
ASAP 2.0에서, 세가지 시간표의 Slot 컴포넌트와 관련된 UI 차이를 정리해보면 다음과 같습니다.
구분 | 가능시간 …
=> [Feat/#285] 시간표 UI 변경 및 Slot 스타일링 로직의 의존성 분리

src/pages/loginEntrance/components/HostComponent.tsx
- close #307 
```
else if (err.response.status === 403) {
console.log(err.response.data.message);
setIsModalOpen(true);
}
```
방장 로그인 api호출시, 방장이 가능시간을 입력하지 않은 상태라면 403에러와 함께 새로운 토큰을 발급받게됩니다.
그런데 기존 코드에서, 가능시간 입력하러 가는 모달만 뜨고 새로운 토큰을 저장하는 로직은 없습니다.
```
else if (err.response.status === 403) {
localStorage.setItem('hostToken', err.response.data.data.accessToken);
setIsModalOpen(true);
}
```
따라서 localStorage에 토큰을 저장하는 로직을 추가하였습니다. (기존의 필요없는 console.log는 삭제)
인증로직도 싹 점검.. 반드시 필요하겠습니다..^^
https://github.com/user-attachments/assets/033f925b-5c34-4585-81f5-51b966c5b4af
=> [Fix/#307] 방장 로그인 403에러시 새로 반환된 토큰 저장

src/pages/createMeeting/CreateMeeting.tsx, src/pages/legacy/selectSchedule/SelectModal.tsx, src/pages/loginEntrance/components/MemberComponent.tsx, src/pages/loginEntrance/components/NoAvailableTimeModal.tsx, src/pages/onBoarding/OnBoarding.tsx, src/pages/selectSchedule/SelectSchedule.tsx, src/pages/selectSchedule/components/selectTimeSlot/TimeSlotCta.tsx, src/pages/steppingStone/SteppingLayout.tsx, src/pages/steppingStone/components/SteppingBtnSection.tsx
- close #311
브라우저 자체 뒤로가기를 대응하기 위한 로직은 다음과 같습니다.
```js
useEffect(
() => {
const goBackFunnel = () => {
setStep((prev) => {
if (prev === 0) {
navigate('/');
return prev;
} else {
return prev - 1;
}
});
};
window.addEventListener('popstate', goBackFunnel);
return () => {
window.removeEventListener('popstate', goBackFunnel);
};
},
[setStep, navigate],
);
const setStepRouter = () => {
navigate(`${location.pathname}?step=${funnelStep[step + 1]}`);
setStep((prev) => prev + 1);
};
```
1. popstate이벤트 리스너에 goBackFunnel을 등록한다.
2. goBackFunnel에서는 step state를 하나 줄여주는 동작을 한다. 이때, 현재 step이 0일 경우 첫 페이지로 가야하기 때문에 navigate('/')을 실행한다.
3. setStepRouter는 funnel 내 다음 버튼에 등록되는 onClick으로서, 다음 step에 해당하는 query string으로 url을 변경한다.
뒤로가기 로직을 점검하면서, 뒤로가기로인해 발생할 수 있는 문제애 대응하기 위해서 살펴보다가
'방장이 뒤로가기하여 시간을 재입력할시'에 대응하는 …
=> [Fix/#311] 뒤로가기 로직 수정

src/components/common/atomComponents/TextInput.tsx, src/pages/createMeeting/components/useFunnel/SetHostInfo.tsx, src/pages/createMeeting/components/useFunnel/SetTitle.tsx, src/pages/loginEntrance/components/HostComponent.tsx, src/pages/loginEntrance/components/MemberComponent.tsx
- close #318
기존에 TextInput 공통컴포넌트에서, 글자수 제한을 15자로 하드코딩되어있었습니다.
TextInput이 쓰이는 곳마다 글자수 제한을 다르게 줄 필요가 있기 때문에 이 값을 prop으로 추가했습니다.
그리고 참여자 정보 입력 input과 방장 정보 입력 input에서 max값을 8자로 넘겨주도록 구현했습니다.
https://github.com/user-attachments/assets/a40702c1-9f55-4b22-a9ed-bd9248379075
=> [Fix/#318] 방장 및 참여자 이름 입력 제한 글자수 8자로 변경
