src/pages/Test.tsx
=> Feat/#1 issue 테스팅

package.json, src/App.tsx, src/pages/ScrollerComponent.tsx, src/styles/globalStyles.ts
=> init: globalStyle적용

.github/workflows/pr-size-labeler.yml
fix: pr size labeler yml 파일 수정
=> fix: pr size labeler yml 파일 수정

src/Router.tsx
=> fix: 중복 라우터 제거

src/Router.tsx, src/assets/svgs/speechBubble.svg, src/components/Icon/icon.ts, src/components/moleculesComponents/Header.tsx, src/components/moleculesComponents/TitleComponents.tsx, src/components/scheduleComponents/components/Row.tsx, src/components/scheduleComponents/components/TimeTable.tsx, src/components/scheduleComponents/utils/getTimeSlots.ts, src/pages/ApiTesting.tsx, src/pages/BestMeetTime/BestMeetTime.tsx, src/pages/LoginEntrance/components/HostComponent.tsx, src/pages/LoginEntrance/components/MemberComponent.tsx, src/pages/createMeeting/CreateMeeting.tsx, src/pages/createMeeting/components/ReturnTitleComponent.tsx, src/pages/selectSchdule/SelectPage.tsx, src/pages/selectSchdule/components/DateDropDown.tsx, src/pages/selectSchdule/components/DateSelect.tsx, src/pages/selectSchdule/components/EndTimeDropDown.tsx, src/pages/selectSchdule/components/EndTimeSelect.tsx, src/pages/selectSchdule/components/SelectSchedule.tsx, src/pages/selectSchdule/components/TimeDropDown.tsx, src/pages/selectSchdule/components/TimeSelect.tsx, src/pages/selectSchdule/types/Schedule.ts, src/pages/selectSchdule/utils/addThirtyMinutesToLastElement.ts, src/pages/selectTime/SelectTime.tsx, src/styles/theme.ts
=> [Feat/available schedule select/#71]

index.html, src/App.tsx, src/utils/changeBrowser.ts
#76 
html2Canvas 안되는것 때문에
-  
카카오톡 링크를 공유하고 큐카드를 다운받으려고 하는데 (html2canvas 를 사용하여)
이미지가 다운받아지지 않는다.
이유를 찾아보니 카카오톡 인앱브라우저에서는 안되는게 당연했다. 안된다고 한다.
따라서 카카오톡 링크를 눌렀을때 크롬이나 사파리 브라우저로 열 수 있도록 해야했다.
그래서 찾아봤는데 안드로이드 폰은 그게 가능했다. 
하지만 ios의 경우 타 브라우저로 여는것이 불가능하다고 했다.
그렇게 포기하려고 하던 순간
[[카카오톡/라인 인앱브라우저에서 외부브라우저 띄우기 (2023.05.04 최신 - inapp browser bypassing)](https://burndogfather.com/271)](https://burndogfather.com/271)
해당 블로그를 통해 ios , android 모두 브라우저를 우회하여 열 수 있는 코드를 제공받았다.
-javascript code
```
<script type='text/javascript' charset='UTF-8'>
var inappdeny_exec_vanillajs = (callback) => {
if(document.readyState != 'loading'){
callback();
}else{
document.addEventListener('DOMContentLoaded', callback);
} 
};
inappdeny_exec_vanillajs(() => { 
/* Do things after DOM has fully loaded */ 
function …
```
=> feat: 카카오톡 인앱브라우저 우회해서 타 브라우저로 열람하는 코드파일

src/pages/ErrorLoading/ErrorPage404.tsx
=> feat: Edit ErrorPageDesign

src/Router.tsx, src/pages/SteppingStone/components/SteppingBtnSection.tsx
=> feat: add memberScheduleComplete Router

src/pages/SteppingStone/components/SteppingBtnSection.tsx, src/pages/createMeeting/CreateMeeting.tsx
=> Feat/host schedule complete view routing/#86

src/pages/LoginEntrance/LoginEntrance.tsx, src/pages/SteppingStone/SteppingLayout.tsx, src/styles/theme.ts, src/utils/apis/axios.ts
localStorage token save and use
=> localStorage token save and use

src/pages/selectSchdule/SelectPage.tsx, src/types/availbleScheduleType.ts
#88 
- 
- 원래 이렇게 말풍선모양인데 밑에 꼬다리는 일단 나중에 하기로 민서랑 상의했습니다
-
=> [Fix/availableScheduleSelectDescription/#88] 회의 상세 설명 문구 조건부 처리 완료

src/components/atomComponents/Button.tsx, src/components/scheduleComponents/components/PriorityDropdown.tsx, src/pages/createMeeting/CreateMeeting.tsx, src/pages/selectSchedule/SelectPriorityPage.tsx, src/types/createAvailableSchduleType.ts, src/utils/apis/createAvailableSchedule.ts
=> Feat/priority view/#111

src/pages/OverallSchedule/OverallSchedule.tsx, src/pages/OverallSchedule/components/Row.tsx, src/pages/OverallSchedule/utils/getFormattedAvailableDateTimes.ts
=> fix: 종합 일정 시간표 에러핸들링

src/components/atomComponents/PasswordInput.tsx, src/components/atomComponents/TextInput.tsx, src/pages/BestMeetTime/ChooseBestTime.tsx, src/pages/BestMeetTime/components/bestMeetTime/AlternativeCard.tsx, src/pages/BestMeetTime/components/bestMeetTime/BestMeetTime.tsx, src/pages/BestMeetTime/components/bestMeetTime/BestTimeCard.tsx
=> fix: ts 오류

src/components/scheduleComponents/utils/compareTime.ts, src/components/scheduleComponents/utils/getTimeSlots.ts, src/pages/selectSchedule/SelectPriorityPage.tsx, src/pages/selectSchedule/SelectSchedulePage.tsx, src/pages/selectSchedule/components/SelectSchedule.tsx
#134 
- 무한 상태관리
- 객체배열 상태관리를 모르겠으면 제 코드를봐주세요
- 제 방법보다 더 좋은 클린코드가 있을거에요
=> Fix/dropdown qa/#134

src/components/scheduleComponents/types/AvailableScheduleType.ts, src/components/scheduleComponents/utils/getTimeSlots.ts, src/pages/OverallSchedule/OverallSchedule.tsx, src/pages/OverallSchedule/components/Row.tsx
=> [Fix/ts bug/#137] ts 오류 수정 (심은서)

src/components/scheduleComponents/components/Column.tsx, src/pages/OverallSchedule/OverallSchedule.tsx, src/pages/OverallSchedule/components/Column.tsx
=> [fix: OverallSchedule/components/Column.tsx ts오류 수정] (심은서)

src/atoms/atom.ts, src/pages/OverallSchedule/OverallSchedule.tsx, src/pages/OverallSchedule/components/Column.tsx
=> fix: OverallSchedule/OverallSchedule.tsx ts오류 수정 (심은서)

src/components/scheduleComponents/components/Row.tsx, src/components/scheduleComponents/types/AvailableScheduleType.ts, src/pages/OverallSchedule/components/Row.tsx, src/pages/OverallSchedule/components/TimeTable.tsx, src/pages/OverallSchedule/utils/getFormattedAvailableDateTimes.ts, src/pages/selectSchedule/SelectSchedulePage.tsx, src/types/availbleScheduleType.ts
=> Fix/ts bug/#137 ts 오류 수정 심은서 완료

src/pages/LoginEntrance/components/MemberComponent.tsx
=> fix: loginMember 토큰 삭제

src/components/scheduleComponents/components/Column.tsx, src/components/scheduleComponents/utils/priorityToColor.ts, src/pages/selectSchedule/SelectSchedulePage.tsx
=> [fix: 시간표 emptydate에 대해 grey9 적용]

src/components/moleculesComponents/Header.tsx, src/components/moleculesComponents/Navigation.tsx
#161 
- 
- 
-
https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/55528304/822b9091-dcf9-4b13-aede-58c7ff7927b8
=> [Feat/tally insert/#161] Navigation 피드백 남기기에 Tally 달기

src/pages/SteppingStone/components/SteppingBody.tsx, src/utils/toast/ToastContainer.tsx
#170 
- height가 조정이 안될 땐 min-height를 주의할것!
- 없다!
- 없다!
=> style: toast height 조정

src/styles/theme.ts
#173 
- font-weight와 굵기 이름 (bold, semi-bold, ...)를 매치하는게 종종 헷갈렸는데, [mdn에서 정리해둔 문서](https://developer.mozilla.org/ko/docs/Web/CSS/font-weight)를 찾았습니다.
- 
-
전
<br/>
후
=> Fix/font weight/#173

src/components/atomComponents/Button.tsx, src/pages/SteppingStone/SteppingLayout.tsx, src/pages/selectSchedule/SelectSchedulePage.tsx, src/styles/theme.ts
- 민서한테 물어봐서 일단 가능시간 입력 부분에만 딤처리 넣었습니다. 우선순위 선정 부분에 넣어야할지 말지는 우선순위 선정을 빼느냐 안빼느냐에 달려있는데 필요해지면 추후 추가하겠습니다!
=> [Design/#189] CTA버튼 딤처리

src/components/atomComponents/Button.tsx, src/pages/selectSchedule/SelectSchedulePage.tsx
- pointer-events:none; 을 하면 마치 그 영역이 없는 것처럼 터치를 무시하고 그 밑에 레이어를 터치하도록 할 수 있다.
https://github.com/ASAP-as-soon-as-possible/ASAP_Client/assets/55528304/c328d98d-68a4-4391-ab2a-0eff35a98941
=> [Feat/#207] 딤처리 영역 터치 무시

src/components/atomComponents/Button.tsx, src/pages/selectSchedule/SelectSchedulePage.tsx
=> [Fix/#211] 버튼 공통컴포넌트 기존으로 복귀 및 CAT dim 따로 처리

src/components/atomComponents/Button.tsx, src/pages/selectSchedule/SelectSchedulePage.tsx
=> release 1.0.2 -> main

src/components/atomComponents/Button.tsx
=> [Hotfix] 스케줄 선택 페이지에서 버튼 안눌리는 문제

src/pages/SteppingStone/components/SteppingBtnSection.tsx
=> fix: 회의생성완료 모달 사이즈 수정

src/pages/onBoarding/OnBoarding.tsx
=>  [배포 자동화 테스트 PR입니다.]

src/pages/onBoarding/OnBoarding.tsx
=> chore: workflows파일 하나로 만들고 action잡는지 확인해보는용도의 커밋

src/pages/loginEntrance/components/IncorrectInfoModal.tsx, src/pages/loginEntrance/components/NoAvailableTimeModal.tsx
- close #326 
릴리즈가 얼마 남지 않은 시점이라 원래있는 모달을 변형하여 사용했습니다.
=> [Fix/#326] 모달 디자인 변경
